name: Deploy Container Image to Azure App Service

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: salespocacr.azurecr.io
        username: salespocacr
        password: 18tpUx09XQh+QVcIYuuc5jAdYJP4PisfGVqE+tC8MK+ACRBKy0h8
    - run: |
        docker build . -t salespocacr.azurecr.io/myapp:${{ github.sha }}
        docker push salespocacr.azurecr.io/myapp:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'mysalespocapiapp'
        images: 'salespocacr.azurecr.io/myapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout